### ISSUE TITLE
Queue purge causing ATTs to be flaky

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureStorageQueues#60] opened 2016-03-30 23:29 UTC
There's something about `When_timeout_dispatch_fails.Should_retry_and_move_to_error` that is flaky or the cleanup is not working properly. All tests/ATTs are passing locally (using Azure storage account). 

This issue has surfaced up when working on PR https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/56

**Comment by Scooletz** [comment] 2016-03-31 09:49
:+1: I've been hit by this on develop. I've seen that the failing was caused by either less or greater number of messages. In one case, after ending the test a message was left in the queue.

A failure example:
https://builds.particular.net/viewLog.html?buildId=155325&tab=buildResultsDiv&buildTypeId=NServiceBus_Transports_NServiceBusAzureStorageQueues_2RunAcceptenceTests

**Comment by SeanFeldman** [comment] 2016-03-31 19:56
For ASQ, is cleanup taking at the end of each test or prior to test execution?

**Comment by dvdstelt** [comment] 2016-03-31 20:01
Prior to

**Comment by SeanFeldman** [comment] 2016-03-31 20:29
After looking into the [`CleanQueuesUsedByTest` ](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/aadad168fc466edee19fe47420f477cf468e8d88/src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs#L48) execution with a debugger, I've noticed that [`GetTestRelatedQueueNames`](https://github.com/Particular/NServiceBus.AzureStorageQueues/blob/aadad168fc466edee19fe47420f477cf468e8d88/src/AcceptanceTests/ConfigureAzureStorageQueueTransport.cs#L65) resolved no queue names... This could be an issue for the cleanup.

**Comment by SeanFeldman** [comment] 2016-03-31 21:32
I have traced through and think the issue is that ATT endpoints are started _after_ cleanup is executed. Hence the empty `QueueBindings`. Wonder if this is a recent change in ATTs/core.

**Comment by dvdstelt** [comment] 2016-04-01 06:46
You merged it 20 days ago! :)
https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/52

**Comment by SeanFeldman** [comment] 2016-04-01 07:44
@dvdstelt what I meant is "if there _was_ a change to ATTs/core _recently_". I assume you guys had it working.

**Comment by Scooletz** [comment] 2016-04-01 08:00
I remember that queues were returned when I changed this implementation from "clear all" to "clear ones that are used". I might remember it wrong, but it's highly unlikely. I think we need to adjust it. I would rather not go through all the queues - that would be much slower.

**Comment by dvdstelt** [comment] 2016-04-01 09:01
Cleaning all just takes a few seconds, on tests that run for quite a while. Makes implementation easier as well. I don't see any reason not too.

**Comment by Scooletz** [comment] 2016-04-01 09:13
The `QueueBindings` are empty now. I'm going to do the parallel `Clear` as you mentioned before. No time for debugging right now.

**Comment by tmasternak** [comment] 2016-04-01 11:33
@SeanFeldman this has not been scheduled for work. Please add `Consider for Promotion` if you want this one to considered for starting.

**Comment by SeanFeldman** [comment] 2016-04-01 18:10
@tmasternak this task was impeding other tasks (false failures on builds), making it a road-blocker that needed to be removed. Is it wise to discussed and prioritized with squad? I'd think it's up to the maintainer group to resolve it. Thoughts?

**Comment by distantcam** [comment] 2016-04-04 01:28
What issue or PR is this blocking? It's unclear. #56 is merged and mentions problems with #57 which is on hold.

If an issue is blocked, it would fall out of the WIP, allowing this issue to go into progress.

**Comment by SeanFeldman** [comment] 2016-04-04 04:22
@distantcam I have took the liberty to merge #56 despite the failing test. Following the logic you've outlined, this issue should be handled as a part of #56. Or, alternatively, as a part of #43 (as it is part of `v6 launch`).

**Comment by distantcam** [comment] 2016-04-04 04:25
@SeanFeldman #56 is merged, which means it's complete. If there's still a problem that should be a separate issue. Whatever is the current issue that's being worked on should be in the WIP, and if this issue is blocked because of that it should come out of the WIP.

**Comment by SeanFeldman** [comment] 2016-04-04 04:30
@distantcam this **is** the (separate) issue we're talking about.

**Comment by distantcam** [comment] 2016-04-04 04:31
@SeanFeldman Right. So what in progress issue is blocked waiting for this?

**Comment by SeanFeldman** [comment] 2016-04-04 04:33
Thought this comment https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/60#issuecomment-205131567 has explained it. If I'd wait with #56, it would be blocked by this issue.

**Comment by adamralph** [comment] 2016-04-04 12:21
Is this a bug in the package? Or some tech debt in the tests?

**Comment by Scooletz** [comment] 2016-04-04 12:37
The solution for this has been merged to `develop` already.

**Closed** 2016-04-04 12:36 UTC
Labels: Type: Bug
